name: Tests
on: push
jobs:
  testing:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        python-version:
          - '3.13'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          apt install -y adduser base-files bash bash-completion command-not-found cron debconf distro-info-data e2fsprogs fuse3 gettext-base hdparm iproute2 keyutils libattr1:amd64 libaudit-common libbpf0:amd64 libbsd0:amd64 libbz2-1.0:amd64 libc-bin libc6:amd64 libcap2:amd64 libelf1:amd64 libexpat1:amd64 libffi8:amd64 libgcc-s1:amd64 liblzma5:amd64 libmagic1:amd64 libmd0:amd64 libmecab2:amd64 libmnl0:amd64 libpam-runtime libpcre2-8-0:amd64 libpython3.10-minimal:amd64 libpython3.10-stdlib:amd64 libpython3.13-stdlib:amd64 libreadline8:amd64 libsensors-config libssl3:amd64 libtinfo6:amd64 libtirpc-common libuuid1:amd64 locales login logrotate lsb-release ltrace mailcap man-db media-types multipath-tools nano ncurses-base netbase nftables openssl overlayroot procps python3-apport python3-minimal python3-zope.interface python3.10-minimal python3.13 rsyslog screen sudo tar tzdata ucf unixodbc-common usb-modeswitch walinuxagent wget zlib1g:amd64
          pip install tox==4.28.0 wheel==0.45.1
      - run: |
          python -m pip install --upgrade pip tox codecov cuvner
      - run: |
          python --version
      - run: |
          tox -e coverage
    env:
      COLUMNS: '254'
      LC_ALL: C.utf8
      LC_CTYPE: C.UTF-8
      LINES: '62'
      PYTHONHASHSEED: '1573868627'
      PYTHONIOENCODING: utf-8
      TERM: xterm
  flake8:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        python-version:
          - '3.13'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          apt install -y adduser base-files bash bash-completion command-not-found cron debconf distro-info-data e2fsprogs fuse3 gettext-base hdparm keyutils libattr1:amd64 libaudit-common libc-bin libc6:amd64 libmagic1:amd64 libmecab2:amd64 libpam-runtime libpcre2-8-0:amd64 libpython3.13-stdlib:amd64 libsensors-config libtirpc-common locales login logrotate lsb-release ltrace mailcap man-db media-types multipath-tools nano ncurses-base netbase nftables openssl overlayroot procps python3-minimal python3-zope.interface python3.10-minimal python3.13 rsyslog screen sudo tar tzdata ucf unixodbc-common usb-modeswitch walinuxagent wget
          pip install tox==4.28.0 wheel==0.45.1
      - run: |
          python -m pip install --upgrade pip tox
      - run: |
          python --version
      - run: |
          tox -e flake8less
    env:
      COLUMNS: '254'
      LC_CTYPE: C.UTF-8
      LINES: '62'
      PYTHONHASHSEED: '1006174280'
      PYTHONIOENCODING: utf-8
      TERM: xterm
